<!DOCTYPE html>
<html>
<head>
	<title>Cookie</title>
	<style type="text/css">
		img {
			width: 100px;
			height: 100px;
		}

		.place {
			text-align: center;
			border: 3px solid #c1c1c1;
			border-radius: 10px;
			padding: 20px;
			margin: 20px;
			width: 150px;
			display: inline-block;
		}

		footer {
			background-color: #c1c1c1;
			font-size: small;
			text-align: center;
			margin: 20px 0px;
			padding: 5px;
		}
	</style>
</head>
<body>
	<div id="menu">
		<a href="/cookies">Cookies</a>
		<a href="/cookies/new">New cookie</a>
		<a href="/logout">Logout</a>
	</div>

	<?= $this->getContent() ?>

	<footer>
		Cookies By TechLaunch
	</footer>
</body>
</html>